name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # 매일 오전 3시 KST (UTC 기준 18시)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate 3D Profile SVG
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Force Push
        env:
          TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git

          git add -A
          git commit -m "generated" || echo "No changes to commit"
          git push --force origin HEAD:main
